// Generated clip entries — paste into preinstalledVideos.js
const NEW_CLIPS = [
  {
    id: "clip_cinematic_1",
    name: "Faceless 1",
    category: "cinematic",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/faceless.mp4",
  },
  {
    id: "clip_cinematic_2",
    name: "Faceless 2",
    category: "cinematic",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/faceless_1.mp4",
  },
  {
    id: "clip_cinematic_3",
    name: "Faceless 3",
    category: "cinematic",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/faceless_3.mp4",
  },
  {
    id: "clip_cinematic_4",
    name: "Faceless 4",
    category: "cinematic",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/faceless_5.mp4",
  },
  {
    id: "clip_cinematic_5",
    name: "Faceless 5",
    category: "cinematic",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/faceless_11.mp4",
  },
  {
    id: "clip_cinematic_6",
    name: "Faceless 6",
    category: "cinematic",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/faceless_12.mp4",
  },
  {
    id: "clip_cinematic_7",
    name: "Faceless 7",
    category: "cinematic",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/faceless_17.mp4",
  },
  {
    id: "clip_cinematic_8",
    name: "Faceless 8",
    category: "cinematic",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/faceless_26.mp4",
  },
  {
    id: "clip_cinematic_9",
    name: "Faceless 9",
    category: "cinematic",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/faceless_30.mp4",
  },
  {
    id: "clip_cinematic_10",
    name: "Faceless 10",
    category: "cinematic",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/faceless_34.mp4",
  },
  {
    id: "clip_luxury_11",
    name: "Luxe 2",
    category: "luxury",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/luxe_2.mp4",
  },
  {
    id: "clip_luxury_12",
    name: "Luxe 10",
    category: "luxury",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/luxe_10.mp4",
  },
  {
    id: "clip_luxury_13",
    name: "Luxe 19",
    category: "luxury",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/luxe_19.mp4",
  },
  {
    id: "clip_luxury_14",
    name: "Luxe 28",
    category: "luxury",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/luxe_28.mp4",
  },
  {
    id: "clip_luxury_15",
    name: "Luxe 37",
    category: "luxury",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/luxe_37.mp4",
  },
  {
    id: "clip_luxury_16",
    name: "Luxe 42",
    category: "luxury",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/luxe_42.mp4",
  },
  {
    id: "clip_luxury_17",
    name: "Luxe 58",
    category: "luxury",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/luxe_58.mp4",
  },
  {
    id: "clip_luxury_18",
    name: "Luxe 67",
    category: "luxury",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/luxe_67.mp4",
  },
  {
    id: "clip_luxury_19",
    name: "Luxe 78",
    category: "luxury",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/luxe_78.mp4",
  },
  {
    id: "clip_luxury_20",
    name: "Luxe 106",
    category: "luxury",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/luxe_106.mp4",
  },
  {
    id: "clip_luxury_21",
    name: "Luxe 131",
    category: "luxury",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/luxe_131.mp4",
  },
  {
    id: "clip_luxury_22",
    name: "Luxe 136",
    category: "luxury",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/luxe_136.mp4",
  },
  {
    id: "clip_luxury_23",
    name: "Luxe 138",
    category: "luxury",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/luxe_138.mp4",
  },
  {
    id: "clip_luxury_24",
    name: "Luxe 168",
    category: "luxury",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/luxe_168.mp4",
  },
  {
    id: "clip_luxury_25",
    name: "Luxe 178",
    category: "luxury",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/luxe_178.mp4",
  },
  {
    id: "clip_aesthetic_26",
    name: "Aesthetic 271",
    category: "aesthetic",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/aesthetic_271.mp4",
  },
  {
    id: "clip_aesthetic_27",
    name: "Aesthetic 280",
    category: "aesthetic",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/aesthetic_280.mp4",
  },
  {
    id: "clip_aesthetic_28",
    name: "Aesthetic 290",
    category: "aesthetic",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/aesthetic_290.mp4",
  },
  {
    id: "clip_aesthetic_29",
    name: "Aesthetic 300",
    category: "aesthetic",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/aesthetic_300.mp4",
  },
  {
    id: "clip_aesthetic_30",
    name: "Aesthetic 312",
    category: "aesthetic",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/aesthetic_312.mp4",
  },
  {
    id: "clip_aesthetic_31",
    name: "Aesthetic 324",
    category: "aesthetic",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/aesthetic_324.mp4",
  },
  {
    id: "clip_aesthetic_32",
    name: "Aesthetic 341",
    category: "aesthetic",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/aesthetic_341.mp4",
  },
  {
    id: "clip_aesthetic_33",
    name: "Aesthetic 360",
    category: "aesthetic",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/aesthetic_360.mp4",
  },
  {
    id: "clip_aesthetic_34",
    name: "Aesthetic 369",
    category: "aesthetic",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/aesthetic_369.mp4",
  },
  {
    id: "clip_aesthetic_35",
    name: "Aesthetic 390",
    category: "aesthetic",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/aesthetic_390.mp4",
  },
  {
    id: "clip_aesthetic_36",
    name: "Aesthetic 405",
    category: "aesthetic",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/aesthetic_405.mp4",
  },
  {
    id: "clip_aesthetic_37",
    name: "Aesthetic 419",
    category: "aesthetic",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/aesthetic_419.mp4",
  },
  {
    id: "clip_aesthetic_38",
    name: "Aesthetic 424",
    category: "aesthetic",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/aesthetic_424.mp4",
  },
  {
    id: "clip_aesthetic_39",
    name: "Aesthetic 430",
    category: "aesthetic",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/aesthetic_430.mp4",
  },
  {
    id: "clip_aesthetic_40",
    name: "Aesthetic 545",
    category: "aesthetic",
    thumbnail: "",
    url: "https://bmpxhntqtcgmqghydpxl.supabase.co/storage/v1/object/public/clips/aesthetic_545.mp4",
  }
];

console.log(JSON.stringify(NEW_CLIPS, null, 2));
