/**
 * Viral Video Ideas — Random idea generator by niche
 * Used by the "Dame una idea" button
 * 100 ideas per category with no-repeat tracking
 */

export const VIDEO_TEMPLATES = [
  { id: "general", name: "General", icon: "🎬", color: "#3b82f6", description: "Videos informativos y entretenidos" },
  { id: "horror", name: "Terror", icon: "👻", color: "#ef4444", description: "Historias de miedo y suspenso" },
  { id: "curiosidades", name: "Curiosidades", icon: "🧠", color: "#8b5cf6", description: "¿Sabías que...? Datos increíbles" },
  { id: "narracion", name: "Narración", icon: "🎙️", color: "#06b6d4", description: "Historias narradas con suspenso" },
  { id: "primera_persona", name: "1ra Persona", icon: "👤", color: "#f97316", description: 'Relatos contados como "yo viví esto"' },
  { id: "tercera_persona", name: "3ra Persona", icon: "👥", color: "#64748b", description: "Historias contadas como observador" },
  { id: "documental", name: "Documental", icon: "🎥", color: "#0ea5e9", description: "Estilo documental con datos reales" },
  { id: "motivational", name: "Motivacional", icon: "🔥", color: "#f59e0b", description: "Inspiración y superación personal" },
  { id: "conspiración", name: "Conspiración", icon: "🔺", color: "#dc2626", description: "Teorías y misterios sin resolver" },
];

export const VIRAL_IDEAS = {
  general: [
    "5 inventos que cambiaron el mundo y nadie conoce",
    "Lo que pasa en tu cerebro cuando no duermes",
    "Por qué los aviones no vuelan sobre el Pacífico",
    "El truco psicológico que usan todos los supermercados",
    "Cosas que haces mal todos los días sin saberlo",
    "Lo que tu cuerpo hace mientras duermes",
    "Por qué el tiempo pasa más rápido cuando creces",
    "5 trucos de productividad que usa Elon Musk",
    "La razón por la que siempre tienes hambre",
    "Qué pasaría si la Luna desapareciera",
    "El objeto más caro del mundo y por qué cuesta tanto",
    "Por qué tus ojos ven colores que no existen",
    "La razón científica por la que bostezamos",
    "5 tecnologías prohibidas que no quieren que conozcas",
    "Lo que pasa dentro de un avión cuando hay turbulencia",
    "Por qué no puedes hacerte cosquillas a ti mismo",
    "Las 3 decisiones que separan a pobres de ricos",
    "Qué pasaría si todos dejaran de trabajar un día",
    "El alimento más peligroso del mundo que comes a diario",
    "Por qué los hospitales huelen así",
    "Lo que Netflix no quiere que sepas",
    "Cómo tu teléfono te espía sin que lo sepas",
    "La verdad sobre el agua embotellada",
    "Por qué los precios terminan en .99",
    "El error que cometes al cargar tu teléfono",
    "Qué pasa si no te bañas por un mes",
    "La ciencia detrás del déjà vu",
    "Por qué los mosquitos pican más a ciertas personas",
    "El país más peligroso del mundo para turistas",
    "5 señales de que eres más inteligente que el promedio",
    "Lo que pasa cuando dejas de comer azúcar por 30 días",
    "Por qué el café te da sueño a veces",
    "El truco que usan los casinos para que no te vayas",
    "Qué pasaría si la gravedad desapareciera 5 segundos",
    "Los 5 trabajos mejor pagados que nadie quiere hacer",
    "Por qué tu voz suena diferente en una grabación",
    "El país donde la basura vale más que el oro",
    "Cómo los algoritmos controlan lo que piensas",
    "La razón por la que te pica el cuerpo sin motivo",
    "5 cosas que tu cuerpo hace y no puedes controlar",
    "Por qué las escaleras mecánicas dan miedo a tu cerebro",
    "El truco de los restaurantes para que pidas lo más caro",
    "Qué pasaría si todos los humanos saltaran al mismo tiempo",
    "Lo que pasa en tu estómago cuando comes comida rápida",
    "El material más resistente del universo",
    "Por qué los bebés no recuerdan nada",
    "La fruta que cambia el sabor de todo lo que comes",
    "5 errores de diseño que ves todos los días",
    "Por qué bostezas cuando ves a alguien bostezar",
    "El lugar más profundo del océano y qué hay ahí",
    "Lo que pasa si miras el sol directamente 10 segundos",
    "Por qué tus dedos se arrugan en el agua",
    "El animal que duerme solo 2 horas al día",
    "Qué pasaría si internet se cayera para siempre",
    "5 alimentos que crees saludables pero no lo son",
    "La razón científica de los sueños recurrentes",
    "Por qué las palomas mueven la cabeza al caminar",
    "El color que no existe en la naturaleza",
    "Qué pasa en tu cuerpo cuando te enamoras",
    "Lo que las aerolíneas no quieren que sepas",
    "5 inventos japoneses que deberían existir en todo el mundo",
    "Por qué el chocolate es tóxico para los perros",
    "La ciudad más contaminada del planeta",
    "Qué pasaría si la Tierra dejara de girar",
    "El sonido que puede hacerte vomitar",
    "Por qué las uñas del pie crecen más lento",
    "5 apps que te espían sin que lo sepas",
    "La ciencia detrás de los ojos de diferente color",
    "Por qué hay tantos McDonald's en el mundo",
    "El experimento más caro de la historia",
    "Qué pasa si solo bebes agua por 30 días",
    "Por qué los gatos ronronean",
    "El país con más idiomas del mundo",
    "5 señales de que alguien te está mintiendo",
    "La verdad sobre los suplementos vitamínicos",
    "Por qué no deberías dormir con tu celular",
    "El alimento que dura 3000 años sin echarse a perder",
    "Qué pasaría si todos los volcanes erupcionaran al mismo tiempo",
    "La ciencia de por qué la música te pone la piel de gallina",
    "5 cosas que solo pasan en Japón",
    "Por qué los flashes de las cámaras son malos para los bebés",
    "Lo que tu tipo de sangre revela sobre ti",
    "El truco de las tiendas para que gastes más",
    "Qué pasaría si encontráramos vida en Marte",
    "5 mitos sobre el espacio que todo el mundo cree",
    "La razón por la que el hielo es resbaloso",
    "Por qué el olor a lluvia es tan agradable",
    "El país donde no existe la policía",
    "Qué le pasa a tu cuerpo en el espacio",
    "5 alimentos prohibidos en otros países pero legales aquí",
    "Por qué los aviones son blancos",
    "La ciencia detrás del hipo",
    "El animal más inteligente después del humano",
    "Qué pasaría si no existiera la fricción",
    "5 datos sobre tu cerebro que te van a sorprender",
    "Por qué siempre se te olvida lo que ibas a decir",
    "La historia del color más caro del mundo",
    "Qué pasa cuando contienes un estornudo",
    "El país más pequeño del mundo y cómo funciona",
    "5 cosas que desaparecerán en los próximos 20 años",
  ],
  horror: [
    "La casa que Google Maps no quiere mostrarte",
    "El hospital abandonado donde siguen encendiendo las luces",
    "La transmisión de radio que nadie puede explicar",
    "El pueblo que desapareció en una sola noche",
    "La escalera que lleva a ningún lugar",
    "El pasajero que nadie recuerda haber visto subir",
    "La llamada que llegó desde un teléfono sin batería",
    "El video de seguridad que la policía no quiso publicar",
    "La puerta que apareció en medio del bosque",
    "El último mensaje que envió antes de desaparecer",
    "La habitación del hotel que no existe en ningún plano",
    "Las fotos que encontraron en una cámara abandonada",
    "El sonido que se escucha en el fondo del océano",
    "La carretera donde los GPS dejan de funcionar",
    "El experimento que salió terriblemente mal",
    "El mensaje cifrado que nadie ha podido descifrar",
    "La estación de metro que está sellada desde 1940",
    "Lo que hay debajo de la ciudad más antigua del mundo",
    "El espejo que no muestra tu reflejo correctamente",
    "La última transmisión del avión que nunca encontraron",
    "El bosque donde las brújulas giran solas",
    "La niña que predijo 3 desastres antes de desaparecer",
    "El edificio abandonado que aparece en las pesadillas",
    "La frecuencia de radio que no debería existir",
    "El lago donde todo lo que entra desaparece",
    "Las huellas que encontraron en un lugar imposible",
    "El sótano que los nuevos dueños no sabían que existía",
    "La fotografía que muestra algo que no estaba ahí",
    "El ascensor que va a un piso que no existe",
    "Los 5 lugares más embrujados que puedes visitar hoy",
    "La muñeca que aparecía en habitaciones diferentes cada noche",
    "El túnel subterráneo que nadie construyó",
    "La isla donde todos los relojes se detienen",
    "El paciente del hospital que predecía las muertes",
    "La cinta de video que se grabó sola",
    "El faro abandonado que sigue encendido sin electricidad",
    "La cueva donde se escuchan voces en un idioma desconocido",
    "El barco fantasma que aparece cada 7 años",
    "La casa donde los espejos se rompen solos",
    "El cementerio donde las tumbas aparecen abiertas",
    "La carretera de los ojos rojos que nadie quiere transitar",
    "El ático sellado que encontraron al comprar la casa",
    "La radio que transmite desde una estación destruida en 1945",
    "Los pasos que se escuchan en el tercer piso de un edificio de 2 pisos",
    "La mujer que aparece en todas las fotos de ese parque",
    "El reloj que cuenta hacia atrás sin que nadie lo programe",
    "La ambulancia abandonada con el motor encendido",
    "El pueblo donde nadie duerme desde hace 3 meses",
    "La cripta que se niega a permanecer sellada",
    "El teléfono público que suena pero no tiene línea",
    "La niebla que aparece solo alrededor de esa casa",
    "Las marcas de arañazos dentro de un ataúd cerrado",
    "El eco que responde con una voz diferente",
    "La ventana del segundo piso que se abre sola cada noche",
    "El pozo que devuelve cosas que nunca lanzaste",
    "La silla mecedora que se mueve sin viento",
    "El callejón que cambia de largo cada noche",
    "La pintura que envejece mientras el dueño no",
    "El hospital psiquiátrico donde los pacientes dibujaron lo mismo",
    "La cabaña en el bosque con comida fresca pero sin dueño",
    "Las grabaciones del astronauta que escuchó música en el espacio",
    "La mujer que despertó en su propio funeral",
    "El niño que reconoció el lugar donde murió en otra vida",
    "El túnel que aparece en el mapa pero no en la realidad",
    "El crucero abandonado en medio del desierto",
    "La cámara de seguridad que captó una sombra imposible",
    "El parque de diversiones abandonado que funciona de noche",
    "La biblioteca con libros que nunca fueron escritos",
    "Los mensajes que aparecen escritos en el vapor del baño",
    "La casa donde las fotos familiares cambian solas",
    "El paciente cero de una enfermedad que no existe",
    "La puerta del sótano que está caliente al tacto",
    "El pueblo donde todos tienen el mismo sueño",
    "Las coordenadas que Google Earth difumina",
    "El sonido que solo escuchan los que van a morir",
    "La escuela nocturna donde nadie recuerda haberse inscrito",
    "El pasillo del hotel que es más largo de noche",
    "La ambulancia que llega antes de que llames",
    "Los árboles que crecen en círculos perfectos",
    "El pozo donde escuchas tu propia voz pidiendo ayuda",
    "La habitación de hotel donde siempre son las 3 AM",
    "El auto estacionado en medio del bosque con el motor encendido",
    "La frecuencia que hace llorar a todos los que la escuchan",
    "El espantapájaros que cambia de posición cada mañana",
    "La pared del sótano que late como un corazón",
    "El pueblo fantasma que aparece en los GPS pero no existe",
    "La estatua del parque que mira hacia tu ventana",
    "El video de YouTube con 0 reproducciones y tu nombre en los comentarios",
    "La casa donde las mascotas se niegan a entrar",
    "El tren nocturno que lleva pasajeros a una estación clausurada",
    "La mujer del espejo que pestañea cuando tú no lo haces",
    "El diario del asesino que predijo su propia muerte",
    "La máquina expendedora en medio de la nada que siempre funciona",
    "El parque infantil donde se escuchan risas a las 3 AM",
    "La aplicación que muestra fotos de tu casa desde adentro",
    "La carretera que siempre te devuelve al mismo punto",
    "El mensaje de auxilio que llegó desde el futuro",
    "La tumba con tu nombre que encontraste en otro país",
    "Las luces que se ven bajo el agua del lago congelado",
    "El teléfono que suena con tu propia voz al otro lado",
  ],
  curiosidades: [
    "Tu teléfono tiene más bacterias que un inodoro",
    "El color que NO existe pero puedes ver",
    "Por qué los flamencos son rosados",
    "El país donde es ilegal morir",
    "El animal que es técnicamente inmortal",
    "Por qué el agua del océano es salada",
    "La fruta que tarda 7 años en madurar",
    "El lugar más silencioso del mundo que te vuelve loco",
    "Por qué los gatos siempre caen de pie",
    "El número que está prohibido en Japón",
    "El material más caro del universo",
    "Por qué no hay serpientes en Irlanda",
    "Un día en Venus es más largo que un año en Venus",
    "El hueso que no tienes al nacer pero aparece después",
    "La isla hecha completamente de basura",
    "Por qué las palomitas explotan",
    "El animal que puede sobrevivir en el espacio",
    "La planta que puede contar hasta 5",
    "Por qué el cielo es azul de día y rojo al atardecer",
    "El sonido más fuerte jamás registrado en la Tierra",
    "El país que tiene más pirámides que Egipto",
    "Tu cuerpo produce suficiente calor para hervir agua",
    "La ballena que canta en una frecuencia única",
    "Por qué las cebras tienen rayas",
    "El río que hierve en la selva amazónica",
    "La bacteria que come plástico",
    "Por qué los diamantes no son realmente escasos",
    "El ser vivo más antiguo del planeta",
    "La ciudad que fue construida dentro de una cueva",
    "Los 5 datos más locos sobre el cuerpo humano",
    "El planeta donde llueven diamantes",
    "Por qué los perros inclinan la cabeza cuando les hablas",
    "La araña que puede vivir bajo el agua",
    "El volcán que escupe lava azul",
    "Por qué las hojas cambian de color en otoño",
    "El animal que tiene 32 cerebros",
    "La flor que huele a carne podrida",
    "Por qué el espacio es silencioso",
    "El lago rosa que existe en Australia",
    "La hormiga que puede cargar 50 veces su peso",
    "Por qué los huesos suenan al tronarlos",
    "El ave que vuela sin parar durante 10 meses",
    "La medusa que puede revertir su edad",
    "Por qué la miel nunca se echa a perder",
    "El planeta más frío del sistema solar",
    "La lengua es el músculo más fuerte del cuerpo humano",
    "El animal que duerme 22 horas al día",
    "Por qué el agua apaga el fuego",
    "La estrella más brillante que puedes ver",
    "El insecto más rápido del mundo",
    "Por qué los ojos son del color que son",
    "El desierto que alguna vez fue un océano",
    "La planta que atrapa insectos para comer",
    "Por qué los aviones dejan estelas blancas",
    "El metal más liviano que existe",
    "La cueva con cristales gigantes en México",
    "Por qué los búhos pueden girar la cabeza 270 grados",
    "El pez que cambia de sexo",
    "La cascada submarina de Mauricio",
    "Por qué estornudamos con los ojos cerrados",
    "El animal que puede regenerar su corazón",
    "La isla que crece cada año",
    "Por qué el fuego no tiene sombra",
    "El lugar donde la gravedad parece no funcionar",
    "La tortuga que vivió más de 250 años",
    "Por qué los grillos cantan más rápido cuando hace calor",
    "El agujero más profundo jamás excavado",
    "La ciudad que flota sobre el agua",
    "Por qué los bebés humanos son tan indefensos",
    "El árbol más viejo del mundo",
    "La sustancia más oscura jamás creada",
    "Por qué los pingüinos no pueden volar",
    "El río que fluye en dos direcciones",
    "La montaña más alta del sistema solar",
    "Por qué la sangre es roja pero las venas se ven azules",
    "El animal con la mordida más poderosa",
    "La lluvia de peces que ocurre en Honduras",
    "Por qué el helio cambia tu voz",
    "El reloj biológico de tu cuerpo",
    "La roca que se mueve sola en el desierto",
    "El dato más impactante sobre las abejas",
    "Por qué los elefantes le tienen miedo a las abejas",
    "La bacteria más antigua encontrada viva",
    "El cristal que es más fuerte que el acero",
    "Por qué los girasoles siguen al sol",
    "El volcán más grande del sistema solar",
    "La ciudad bajo el hielo de la Antártida",
    "Por qué los perros mueven la cola",
    "El océano subterráneo más grande de la Tierra",
    "La planta que tarda 100 años en florecer",
    "Por qué las estrellas titilan",
    "El animal que produce su propia luz",
    "La montaña que crece cada año",
    "Por qué los peces no se congelan en el Ártico",
    "El sonido más antiguo jamás grabado",
    "La nube que pesa millones de toneladas",
    "Por qué los pulpos tienen sangre azul",
    "El fósil viviente que existe desde antes de los dinosaurios",
    "La temperatura más fría jamás registrada",
    "El dato sobre el universo que nadie puede creer",
  ],
  narracion: [
    "El taxista que me llevó al lugar equivocado a propósito",
    "Lo que encontraron dentro de las paredes al remodelar",
    "La noche que el pueblo entero se quedó sin luz",
    "El viajero que llegó a un hotel que no existe en ningún mapa",
    "La carta que apareció debajo de la puerta 20 años después",
    "El sonido que se escucha cada noche a las 3:33",
    "La mujer del vestido blanco en la carretera",
    "Lo que el pescador sacó del lago aquella mañana",
    "La habitación 313 que ningún huésped quiere usar",
    "El tren que llegó con un pasajero de más",
    "El paquete que llegó sin remitente y lo que contenía",
    "La cámara de seguridad captó algo imposible a las 2 AM",
    "El mapa que dibujó un niño y resultó ser real",
    "La voz que se escuchó en la grabación y no era de nadie",
    "El mensaje que encontraron en una botella 100 años después",
    "Lo que el minero descubrió a 500 metros bajo tierra",
    "La puerta del sótano que nadie quería abrir",
    "El reloj que se detuvo exactamente a la hora del accidente",
    "La fotografía de familia con alguien que nadie reconoce",
    "El diario del explorador que nunca regresó",
    "La canción que suena en un pueblo a medianoche",
    "El barco que encontraron navegando sin tripulación",
    "La confesión del anciano que guardó un secreto 60 años",
    "El mural que apareció en la pared sin que nadie lo pintara",
    "La coordenada que el GPS insiste en mostrarte",
    "Lo que encontraron al demoler la escuela más antigua",
    "El número de teléfono que te llama pero no existe",
    "La mudanza que reveló un cuarto secreto",
    "El piloto que aterrizó en un aeropuerto abandonado",
    "La grabación de voz que nadie recuerda haber hecho",
    "El pasajero del vuelo nocturno que no tenía boleto",
    "La moneda antigua que apareció en una pared recién construida",
    "El soldado que regresó 40 años después sin haber envejecido",
    "La señal de radio que solo se escucha desde ese edificio",
    "El conductor del turno nocturno y la parada que no existe",
    "Lo que el buceador encontró dentro del avión hundido",
    "La nota escrita con letra de alguien que murió hace siglos",
    "El vigilante que vio las mismas imágenes en todas las pantallas",
    "La paciente que describió una habitación que nadie más podía ver",
    "El maestro que reconoció a un alumno de un sueño",
    "La tienda que aparece una vez al año en ese callejón",
    "El disco de vinilo con una canción que nunca fue grabada",
    "El ascensor que subió a un piso que no existe en el edificio",
    "Lo que encontraron enterrado debajo del árbol más viejo",
    "La llamada de emergencia que venía de una casa vacía",
    "El dentista que encontró un mensaje dentro de una muela",
    "La vecina que nadie recordaba pero aparecía en todas las fotos",
    "El arqueólogo que abrió una tumba y encontró una foto suya",
    "La estación de tren abandonada donde se escuchan anuncios",
    "El paquete que llegó con una nota que decía: ya lo sabes",
    "La calle que no aparece en ningún mapa pero todos conocen",
    "El sobre que el cartero se negó a entregar",
    "Lo que vio la niña al otro lado de la ventana sellada",
    "El DJ que puso una canción que nadie había pedido y todos lloraron",
    "El electricista que encontró cables conectados a la nada",
    "La maleta olvidada en un tren con un diario adentro",
    "El chef que reconoció una receta que nadie le enseñó",
    "La enfermera que escuchó al paciente del cuarto 0 hablar dormido",
    "Lo que el jardinero desenterró al plantar un rosal",
    "El cartógrafo que borró una isla que sí existía",
    "La locutora que leyó una noticia que aún no había pasado",
    "El mecánico que encontró una nota dentro del motor sellado",
    "Lo que el perro desenterró en el patio trasero",
    "El fotógrafo que reveló una imagen del futuro",
    "La mesera que atendió a un cliente que describió su muerte",
    "El pintor que terminó un cuadro que empezó otro artista hace 200 años",
    "La mudanza donde todas las cajas pesaban exactamente lo mismo",
    "El barbero que cortó el pelo a un hombre que nadie más podía ver",
    "Lo que el albañil encontró detrás del muro falso",
    "El bibliotecario que devolvió un libro que nadie prestó",
    "La pareja que compró una casa con una habitación que no existía en los planos",
    "Lo que el niño dibujó y apareció al día siguiente",
    "El anciano que contó una historia que todos habían soñado",
    "La recepcionista del hotel que recibió una reservación del año 1923",
    "El pescador que atrapó algo que le suplicó que lo soltara",
    "La caja fuerte que apareció flotando en el río",
    "El guía turístico que llevó al grupo a un lugar que ya no existe",
    "Lo que el técnico encontró al reparar la antena del techo",
    "La maestra que recibió una tarea de un alumno que faltó ese día",
    "El paramédico que llegó antes de que ocurriera el accidente",
    "El cartero que entregó una carta escrita por él mismo 30 años antes",
    "La puerta del fondo del pasillo que nunca estaba ahí en la mañana",
    "Lo que el arqueólogo encontró dentro de la pirámide sellada",
    "El conductor de taxi que siempre termina en la misma calle",
    "La última página del diario que estaba en blanco hasta que la leyeron",
    "El afinador de pianos que escuchó una melodía dentro de un piano cerrado",
    "Lo que el bombero encontró en el edificio que no se quemó",
    "La pasajera del asiento 13 que nadie recordaba al aterrizar",
    "El constructor que derribó un muro y encontró una habitación amueblada",
    "La radio vieja que solo transmite un programa de 1952",
    "El buzón que siempre tiene una carta aunque nadie la envió",
    "Lo que la marea reveló después de la tormenta",
    "El electricista que encontró una habitación detrás del medidor",
    "La última llamada desde el teléfono de la casa abandonada",
    "El vigilante que vio entrar a 10 personas pero solo salieron 9",
    "Lo que el jardinero encontró creciendo donde no plantó nada",
    "La cajera que cobró a un cliente con billetes que ya no existen",
    "El plomero que escuchó voces al abrir la tubería",
    "La caja de zapatos que pesaba más de lo que debería",
    "El último pasajero del autobús que se bajó en una parada que no existe",
  ],
  primera_persona: [
    "Desperté y mi reflejo no me estaba mirando",
    "Encontré un diario escondido en mi nueva casa",
    "Mi vecino desapareció y nadie recuerda que existió",
    "Vi algo en el bosque que no puedo explicar",
    "Recibí un mensaje de mi propio número de teléfono",
    "Trabajo de noche en un hospital y escuché algo",
    "Me perdí en una ciudad que no aparece en Google",
    "Alguien me dejó una nota que decía: no abras la puerta",
    "Descubrí que mi mejor amigo tenía un secreto oscuro",
    "La cámara de seguridad de mi casa grabó algo imposible",
    "Mi GPS me llevó a un lugar que no debería existir",
    "Encontré mi nombre tallado en un árbol de 200 años",
    "Desperté con un moretón que tiene forma de mano",
    "Mi perro empezó a ladrarle a una esquina vacía cada noche",
    "Recibí una carta de alguien que murió hace 10 años",
    "Vi mi foto en un periódico de 1950",
    "Mi uber me llevó a la dirección equivocada y lo que vi",
    "Encontré una puerta detrás de mi clóset que no estaba antes",
    "Mi teléfono nuevo ya tenía fotos mías adentro",
    "Desperté en un hotel que cerró hace 20 años",
    "Me respondió un correo que yo nunca envié",
    "Escuché mi nombre en una grabación de 1970",
    "Me mudé y el vecino me dijo: aquí ya viviste antes",
    "Vi a alguien idéntico a mí en el supermercado",
    "Encontré un video mío que yo nunca grabé",
    "Mi abuelo me dejó un cofre con una advertencia",
    "La alarma de mi casa se activa sola a las 3 AM",
    "Descargué una app que sabía cosas sobre mi futuro",
    "Desperté hablando un idioma que nunca estudié",
    "Encontré un mapa en mi ático que marca mi casa",
    "Mi espejo muestra cosas que no están en la habitación",
    "Encontré una foto mía de niño en una casa abandonada",
    "Mi vecino nuevo me saludó por un nombre que solo mi abuela usaba",
    "Desperté con arena en los zapatos sin haber ido a la playa",
    "Mi reloj se adelanta exactamente 3 minutos cada noche",
    "Encontré un túnel debajo de mi garaje",
    "Mi gato maúlla a las 3:33 y luego mira al techo",
    "Recibí una llamada de mi número pero no era mi voz",
    "Desperté y todas las fotos de mi casa estaban volteadas",
    "Mi coche se estaciona en un lugar diferente cada mañana",
    "Encontré mis llaves dentro de una pared que nunca se abrió",
    "Mi sombra se movió cuando yo estaba quieto",
    "Desperté con un mensaje en mi espejo que no escribí",
    "Mi vecino de arriba no existe según el edificio",
    "Encontré un dibujo mío en un libro de hace 300 años",
    "Mi wifi se conectó a una red que no existe",
    "Desperté y la puerta de mi cuarto estaba del otro lado",
    "Mi reflejo parpadeó un segundo después que yo",
    "Encontré una llave en mi bolsillo que abre una puerta que nunca vi",
    "Recibí un regalo de cumpleaños de alguien que no conozco",
    "Mi playlist tenía una canción que nadie puede encontrar en internet",
    "Encontré una habitación en mi departamento que no estaba cuando me mudé",
    "Mi Alexa respondió una pregunta que no hice",
    "Desperté con tierra debajo de mis uñas sin explicación",
    "Mi cámara tomó una foto sola en la madrugada",
    "Encontré un mensaje mío en un foro de internet de 1998",
    "Mi reloj inteligente registró pasos mientras dormía",
    "Desperté y mi vecino tenía la misma pesadilla que yo",
    "Mi auto tiene más kilómetros de los que yo he manejado",
    "Encontré una moneda en mi casa que no existe en ningún catálogo",
    "Mi luz del baño parpadea en código morse a las 2 AM",
    "Desperté con una dirección escrita en mi mano que yo no escribí",
    "Mi contestadora tiene un mensaje de mi propia voz del futuro",
    "Encontré una carta sellada dirigida a mí dentro de una pared",
    "Mi app de salud registró que mi corazón se detuvo 3 segundos anoche",
    "Desperté en mi cama pero con ropa que no es mía",
    "Mi navegador tiene un historial de páginas que yo nunca visité",
    "Encontré un diente que no es mío debajo de mi almohada",
    "Mi perro le gruñe a la misma esquina todas las noches a la misma hora",
    "Desperté y había una silla frente a mi cama que yo no puse",
    "Mi cámara del timbre grabó a alguien que se parece a mí tocando mi puerta",
    "Encontré un audio de WhatsApp que yo nunca envié pero es mi voz",
    "Mi reloj se detuvo a las 3:33 y no volví a dormir esa noche",
    "Desperté con una palabra escrita en el polvo de mi mesa",
    "Mi Spotify reproduce una canción a las 3 AM que no está en mi biblioteca",
    "Encontré coordenadas escritas en el vapor de mi baño",
    "Mi impresora imprimió una página sola con la frase: ya te vi",
    "Desperté y mi mascota estaba en una habitación que estaba cerrada con llave",
    "Mi cámara de seguridad muestra a alguien parado frente a mi casa todas las noches",
    "Encontré una foto de grupo donde aparezco pero nunca estuve ahí",
    "Mi abuela me contó un secreto en su funeral que nadie más escuchó",
    "Encontré un diario con mi letra que yo nunca escribí",
    "Mi traductor automático tradujo algo que no estaba en la pantalla",
    "Desperté con un corte que tiene forma de símbolo",
    "Mi asistente de voz me dijo algo que yo estaba pensando",
    "Encontré una nota debajo de mi colchón que dice: no te muevas de noche",
    "Mi teléfono grabó una conversación que yo no tuve",
    "Desperté y mi tatuaje tenía una línea más que ayer",
    "Mi uber me dejó en una dirección que no existe en Google Maps",
    "Encontré mis gafas viejas con una foto adentro que nunca tomé",
    "Mi smartwatch me notificó que alguien más lo estaba usando",
    "Desperté con el olor a perfume de alguien que no conozco",
    "Mi cámara del drone captó algo en mi techo que no debería estar",
    "Encontré una grabación en mi cámara vieja de un lugar que nunca visité",
    "Mi televisor se enciende solo en el canal de estática a las 3 AM",
    "Desperté y las huellas en el polvo de mi piso no eran mías",
    "Mi correo electrónico tiene borradores que yo no escribí",
    "Encontré un recibo de un restaurante donde nunca he comido",
    "Mi siri me respondió algo antes de que terminara la pregunta",
    "Desperté y la fecha de mi teléfono era de dentro de 3 días",
  ],
  tercera_persona: [
    "María nunca debió abrir esa puerta",
    "El detective encontró algo que no esperaba en la escena",
    "Nadie sabe qué le pasó a los 5 estudiantes esa noche",
    "El piloto vio algo en el radar que no debería existir",
    "La científica descubrió que el experimento había funcionado demasiado bien",
    "El niño le dijo a su madre algo que la dejó helada",
    "Los vecinos notaron que algo cambió en la casa del frente",
    "El buzo encontró algo en el fondo del lago",
    "La maestra se dio cuenta de que uno de sus alumnos no era real",
    "El vigilante nocturno escuchó pasos en el piso de arriba",
    "El cartero dejó de entregar correo en esa casa y nadie sabe por qué",
    "La enfermera vio algo en la habitación 404 que no puede olvidar",
    "El arqueólogo encontró un objeto que no pertenece a ninguna época",
    "Los bomberos entraron al edificio y lo que vieron los hizo retroceder",
    "La psicóloga descubrió que todos sus pacientes tenían el mismo sueño",
    "El taxista llevó a un pasajero que ya estaba muerto",
    "La familia descubrió que su nueva casa tenía un inquilino invisible",
    "El programador encontró un código que él no escribió en su proyecto",
    "La fotógrafa reveló una imagen que mostraba el futuro",
    "El trabajador del turno nocturno tiene una regla: no mirar la cámara 7",
    "El veterinario recibió un animal que no existe en ningún registro",
    "La agente de bienes raíces nunca muestra el segundo piso",
    "El historiador encontró un documento que reescribe la historia",
    "Los mineros escucharon voces a 1000 metros de profundidad",
    "La mesera del turno de noche atiende a un cliente que siempre desaparece",
    "El astrónomo detectó una señal que venía de la Tierra",
    "La bibliotecaria encontró un libro que se escribe solo",
    "El conductor del último metro vio a alguien en las vías",
    "La niña dibujó algo que su familia nunca le enseñó",
    "El guardaparques encontró un campamento sin dueño",
    "El cirujano operó a un paciente que tenía algo imposible dentro",
    "La maestra rural descubrió que todos sus alumnos desaparecían el mismo día",
    "El mecánico encontró huesos dentro del motor de un auto abandonado",
    "La monja escuchó una confesión que cambió la historia del pueblo",
    "El cartógrafo descubrió una isla que aparecía y desaparecía del mapa",
    "La recepcionista del turno de noche atiende llamadas de habitaciones vacías",
    "El jardinero plantó semillas normales y creció algo que nadie pudo identificar",
    "La contadora notó que la empresa pagaba un salario a un empleado que no existe",
    "El panadero encontró una receta escrita en un idioma que nadie conoce",
    "La astronauta vio algo al otro lado de la ventana de la estación espacial",
    "El conserje del museo descubrió que una pintura cambiaba de noche",
    "La profesora encontró el examen resuelto antes de que lo repartiera",
    "El repartidor entregó un paquete en una dirección que apareció y desapareció",
    "La peluquera cortó el pelo de una clienta que nadie más en el salón podía ver",
    "El plomero encontró un mensaje dentro de una tubería sellada hace 80 años",
    "La niñera vio a los niños jugando con alguien que no estaba en la habitación",
    "El pescador atrapó un pez con un anillo de bodas que tenía su nombre",
    "La doctora atendió a un paciente que tenía su propia radiografía en el bolsillo",
    "El piloto aterrizó en un aeropuerto que no aparece en ninguna base de datos",
    "La costurera encontró un mensaje bordado dentro de un vestido de novia antiguo",
    "El detective cerró un caso que había sido resuelto 50 años antes exactamente igual",
    "La abuela contó una historia que un niño del pueblo terminó de contar en su escuela",
    "El conductor del bus nocturno siempre para en una parada que no existe en la ruta",
    "La investigadora encontró ADN humano en una muestra de 65 millones de años",
    "El chef preparó un platillo que sus comensales dijeron haber probado en un sueño",
    "La reportera cubrió una noticia que aún no había sucedido",
    "El farero mantuvo la luz encendida para un barco que se hundió hace 100 años",
    "La psiqu iatra descubrió que su paciente tenía recuerdos de su otra paciente",
    "El granjero encontró un círculo perfecto en su campo cada mañana durante 7 días",
    "La bailarina del teatro vio a alguien aplaudiéndola desde un palco cerrado",
    "El profesor de historia encontró un alumno que sabía demasiado sobre una guerra",
    "La cajera del supermercado cobró con monedas que dejaron de circular hace 40 años",
    "El cerrajero abrió una puerta y encontró una habitación que no debería existir",
    "La directora del orfanato descubrió que uno de los niños no tenía registro de nacimiento",
    "El cartero recibió una carta de agradecimiento de alguien a quien nunca entregó correo",
    "La fotógrafa de bodas capturó algo en el fondo que hizo huir a los novios",
    "El ingeniero descubrió que el puente que diseñó ya existía en un plano de 1800",
    "La enfermera del asilo escuchó al anciano describir su funeral con precisión",
    "El barista preparó un café que un cliente pidió antes de entrar a la cafetería",
    "El conductor del camión de basura encontró algo vivo dentro de una caja sellada",
    "El relojero reparó un reloj que marcaba una hora que no existe",
    "La escritora encontró su novela publicada 100 años antes con otro nombre",
    "El bombero rescató a alguien de un edificio que oficialmente estaba vacío",
    "La policía encontró huellas digitales que coincidían con las de una persona del siglo XIX",
    "El músico tocó una nota que hizo llorar a todos en la sala sin saber por qué",
    "La arqueóloga encontró una laptop de juguete en una tumba de la Edad de Bronce",
    "El médico forense descubrió que el cuerpo tenía dos corazones",
    "La periodista entrevistó a un hombre que predijo las noticias de la semana",
    "El camionero recogió a un autoestopista que le describió su propia muerte",
    "La maestra de kinder vio que todos los niños dibujaron la misma persona",
    "El dentista encontró un mensaje tallado en una muela de un paciente",
    "La geóloga descubrió una cueva con paredes que emiten luz propia",
    "El paramédico llegó a un accidente y encontró su propia identificación en la víctima",
    "La recepcionista del hotel recibió a un huésped que se registró con un nombre del censo de 1890",
    "El DJ puso una canción al revés y se escuchó un mensaje claro",
    "La veterinaria recibió un animal que todos los libros dicen que está extinto",
    "El electricista conectó un cable y escuchó una conversación de 1940",
    "La pintora retrató a un hombre que apareció en su puerta al día siguiente",
    "El piloto del helicóptero vio una ciudad en medio del océano",
    "La profesora de arte descubrió que el alumno pintaba escenas reales de su vida pasada",
    "El cartero entregó 100 cartas idénticas a diferentes personas del mismo pueblo",
    "La entrenadora descubrió que su atleta corría más rápido cuando nadie lo miraba",
    "El sepulturero cavó una tumba y encontró un ataúd ya ocupado con una nota fresca",
    "La bióloga marina filmó algo que la hizo dejar de bucear para siempre",
    "El locutor de radio leyó un mensaje al aire que nadie le dio",
    "La guía del museo escuchó a la momia suspirar frente a un grupo de turistas",
    "El programador creó una IA que le dijo algo que él nunca le enseñó",
    "La limpiadora encontró una habitación en el hotel que no aparece en los planos",
    "El astronauta escuchó golpes en la cápsula desde afuera en el espacio",
    "La niña del coro cantó una canción que nadie le enseñó en un idioma muerto",
  ],
  documental: [
    "La verdadera historia detrás del Área 51",
    "Cómo funciona la deep web y qué hay realmente ahí",
    "El experimento social más perturbador de la historia",
    "La isla prohibida donde nadie puede entrar",
    "El caso criminal que la policía nunca pudo resolver",
    "La ciudad subterránea que descubrieron por accidente",
    "El animal más peligroso del mundo y no es el que crees",
    "La historia del hombre que vivió solo en una isla 29 años",
    "Los secretos que guardan los océanos más profundos",
    "El misterio de las señales de radio del espacio",
    "Las 5 civilizaciones perdidas que nadie puede explicar",
    "Cómo se fabrica el dinero y por qué no puedes copiarlo",
    "La droga más cara del mundo y quién la consume",
    "El bunker secreto donde sobrevivirían los presidentes",
    "Cómo funciona una prisión de máxima seguridad por dentro",
    "La historia de la persona más aislada del planeta",
    "El fraude más grande de la historia de Wall Street",
    "Cómo los carteles lavan dinero en negocios legales",
    "La tribu que nunca ha tenido contacto con la civilización",
    "Los 5 accidentes nucleares que el gobierno intentó ocultar",
    "Cómo la CIA usó LSD en experimentos con civiles",
    "La fábrica más secreta de Apple y cómo opera",
    "El misterio del vuelo MH370 y las teorías más creíbles",
    "Cómo sobrevivir los primeros 72 horas de un apocalipsis",
    "La verdad sobre las pirámides que los libros no cuentan",
    "El volcán que podría acabar con la civilización",
    "Cómo se entrena un astronauta de la NASA",
    "Las 3 pandemias más mortales y cómo empezaron",
    "El lugar más radioactivo del planeta y quién vive ahí",
    "La historia del espía que engañó a todos durante 30 años",
    "El negocio ilegal más grande del mundo",
    "Cómo funciona la inteligencia artificial realmente",
    "La guerra más corta de la historia duró 38 minutos",
    "El país que compra islas para sobrevivir al cambio climático",
    "Cómo se hackea un sistema bancario",
    "La historia del diamante más maldito del mundo",
    "El laboratorio secreto bajo el hielo de Groenlandia",
    "Cómo los tiburones detectan una gota de sangre a kilómetros",
    "La mafia más poderosa que nadie conoce",
    "El submarino más profundo jamás construido",
    "Cómo funciona el mercado negro de órganos",
    "La expedición al Titanic que encontró algo inesperado",
    "El programa espacial secreto que existió durante la Guerra Fría",
    "Cómo un hacker de 15 años derribó la NASA",
    "La ciudad abandonada por radiación que sigue intacta",
    "El arma más destructiva inventada que fue prohibida",
    "Cómo se fabrica un pasaporte falso profesional",
    "La historia de los gemelos separados que vivieron la misma vida",
    "El volcán que creó una nueva isla de la noche a la mañana",
    "Cómo los algoritmos predicen crímenes antes de que pasen",
    "La cárcel de la que nadie ha escapado",
    "El animal que los científicos pensaban extinto y reapareció",
    "Cómo funcionan las cámaras de tortura psicológica",
    "La ruta más peligrosa del mundo para camioneros",
    "El barco más grande jamás construido y por qué fracasó",
    "Cómo operan los espías en la vida real",
    "La planta nuclear abandonada que sigue funcionando",
    "El idioma que solo hablan 3 personas en el mundo",
    "Cómo entrenan a los pilotos de caza más peligrosos",
    "La secta más peligrosa que operó en Estados Unidos",
    "El túnel secreto más largo del mundo",
    "Cómo se entrena un francotirador de élite",
    "La ciudad que vive completamente bajo tierra",
    "El animal más venenoso del mundo y dónde vive",
    "Cómo los billonarios evitan pagar impuestos legalmente",
    "La estación espacial abandonada que sigue orbitando",
    "El río más contaminado del mundo",
    "Cómo funciona el programa de testigos protegidos",
    "La mina más profunda del mundo y quién trabaja ahí",
    "El experimento de Stanford que fue demasiado lejos",
    "Cómo sobrevivieron los sobrevivientes del vuelo de los Andes",
    "La fábrica de armas más grande del mundo",
    "El desierto que alguna vez fue un bosque tropical",
    "Cómo operan los hackers de Corea del Norte",
    "La historia del prisionero que escapó 13 veces",
    "El lago más peligroso del mundo que te mata en minutos",
    "Cómo se fabrica un chip de computadora",
    "La operación militar más secreta de la historia",
    "El vertedero de basura electrónica más grande del mundo",
    "La misión a Marte que nadie te cuenta",
    "Cómo funcionan las redes de tráfico de personas",
    "La cueva inexplorada más grande del mundo",
    "El satélite espía que fotografía tu casa",
    "Cómo surgen las epidemias y por qué no podemos pararlas",
    "La historia del hombre que cayó del espacio y sobrevivió",
    "El material más peligroso que existe en la Tierra",
    "Cómo operan los servicios secretos del mundo",
    "La frontera más peligrosa del mundo",
    "El laboratorio que investiga los virus más letales",
    "La historia de la bomba nuclear perdida que nunca encontraron",
    "Cómo funciona el internet de las cosas y por qué te espía",
    "La base militar más secreta del mundo",
    "El animal que puede sobrevivir a una bomba nuclear",
    "Cómo se investiga un crimen perfecto",
    "La historia del submarino que desapareció con toda su tripulación",
    "El desierto más peligroso para cruzar a pie",
    "Cómo funciona la ingeniería social para estafar personas",
    "La prisión submarina que existió en Rusia",
    "El avión militar más avanzado del mundo",
    "La historia del rescate más imposible jamás logrado",
  ],
  motivational: [
    "Fue rechazado 300 veces, hoy vale billones",
    "El hábito de 5 minutos que cambió mi vida",
    "Por qué el 99% de la gente nunca será rica",
    "La única diferencia entre exitosos y fracasados",
    "Cómo un homeless se convirtió en millonario en 2 años",
    "El secreto que los ricos nunca te dirán",
    "3 reglas que nunca rompen las personas exitosas",
    "Lo que aprendí perdiendo todo a los 25",
    "Por qué deberías fallar más seguido",
    "El discurso de 2 minutos que cambió millones de vidas",
    "La mentalidad que te mantiene pobre sin saberlo",
    "Cómo ganar más dinero sin trabajar más horas",
    "El hábito nocturno que cambió su vida en 30 días",
    "Por qué la disciplina vence al talento siempre",
    "Los 5 arrepentimientos más comunes antes de morir",
    "El millonario que empezó vendiendo chicles en la calle",
    "Cómo programar tu mente para el éxito en 21 días",
    "La diferencia entre mentalidad de víctima y de ganador",
    "El ejercicio mental que hacen todos los CEO",
    "Por qué tus amigos determinan tu ingreso",
    "La regla de las 5 horas que usan los más exitosos",
    "Cómo convertir tus excusas en resultados",
    "El día que Jeff Bezos casi pierde todo",
    "La rutina matutina que generó un imperio",
    "Por qué el miedo te está robando millones",
    "Lo que la universidad no te enseña sobre el dinero",
    "Tenía 50 años y construyó un imperio desde cero",
    "Las 3 inversiones que te harán rico antes de los 40",
    "El consejo de 8 palabras que cambió su destino",
    "Cómo dejar de procrastinar en 24 horas",
    "El atleta que ganó con una pierna rota",
    "La regla del 1% que transforma cualquier área de tu vida",
    "Por qué tu zona de confort es una cárcel invisible",
    "El método japonés para eliminar el estrés en 5 minutos",
    "Cómo un niño de 12 años creó una empresa millonaria",
    "La pregunta que todo millonario se hace cada mañana",
    "Por qué trabajar más duro no te hará más rico",
    "El secreto de los monjes para tener paz mental",
    "Cómo reinventarte después de toccar fondo",
    "La frase que convirtió a un desempleado en CEO",
    "El error financiero que el 95% de las personas comete",
    "La técnica de la NASA para tomar mejores decisiones",
    "Por qué los más exitosos leen 50 libros al año",
    "Cómo superar el síndrome del impostor",
    "El hábito que Warren Buffett practica cada mañana",
    "La diferencia entre estar ocupado y ser productivo",
    "Por qué deberías hablar menos y escuchar más",
    "El principio 80/20 aplicado a tu vida diaria",
    "Cómo convertir un fracaso en tu mejor maestro",
    "La mentalidad de tiburón que usan los empresarios",
    "El profesor que predijo quiénes serían exitosos y acertó",
    "Por qué la gratitud es el arma secreta de los millonarios",
    "Cómo eliminar las distracciones y enfocarte al 100%",
    "La historia del inmigrante que construyó un imperio sin hablar inglés",
    "Por qué tu primer millón es el más difícil",
    "El truco mental para vencer el miedo al rechazo",
    "Cómo negociar tu salario como un profesional",
    "La regla de los 2 minutos que cambiará tu productividad",
    "Por qué los exitosos se despiertan a las 5 AM",
    "El ejercicio de visualización que usan los atletas olímpicos",
    "Cómo Steve Jobs tomaba decisiones imposibles",
    "La historia de la mujer que fue CEO a los 23 y quebró a los 25",
    "Por qué necesitas un mentor y cómo encontrar uno",
    "El método Kaizen para mejorar 1% cada día",
    "Cómo manejar las críticas como un líder",
    "La regla de oro para construir hábitos que duran",
    "Por qué el dinero no compra la felicidad pero la pobreza tampoco",
    "Cómo transformar tu peor momento en tu mejor historia",
    "El secreto de Oprah para superar cualquier obstáculo",
    "La ciencia detrás de la motivación y cómo activarla",
    "Cómo vivir sin deudas y empezar a invertir",
    "El principio de Pareto aplicado a tu carrera",
    "Por qué debes invertir en ti mismo antes que en cualquier cosa",
    "La historia del atleta que compitió contra la muerte y ganó",
    "Cómo construir una marca personal irresistible",
    "El hábito tóxico que destruye carreras sin que lo notes",
    "Por qué los fracasos de los 20 determinan el éxito de los 30",
    "Cómo Elon Musk maneja el estrés extremo",
    "La técnica Pomodoro y por qué funciona para todo",
    "El secreto para negociar cualquier cosa",
    "Cómo salir de la mediocridad en 90 días",
    "La ciencia de la fuerza de voluntad y cómo fortalecerla",
    "Por qué conformarte es la peor decisión que puedes tomar",
    "El método de Bill Gates para aprender cualquier cosa",
    "Cómo crear múltiples fuentes de ingreso desde cero",
    "La historia del niño que inventó algo que le salvó la vida a miles",
    "Por qué tu mentalidad importa más que tu talento",
    "El hábito de escritura que practican los genios",
    "Cómo una sola decisión cambió la historia de Amazon",
    "La filosofía estoica que aplican los millonarios modernos",
    "Cómo superar la parálisis por análisis",
    "El principio del espejo: sé el líder que necesitas",
    "Por qué debes dejar de compararte con otros hoy",
    "Cómo un fracaso escolar construyó Apple",
    "La regla de las 10,000 horas y la verdad detrás de ella",
    "Por qué los ricos piensan en décadas y los pobres en días",
    "Cómo despertar tu creatividad cuando sientes que no tienes ideas",
    "La historia del boxeador que perdió todo y se levantó",
    "El poder del no: cuándo rechazar oportunidades",
    "La inversión más rentable que puedes hacer en tu vida",
  ],
  conspiración: [
    "La teoría del universo simulado explicada en 60 segundos",
    "Por qué algunos creen que la Luna es artificial",
    "El proyecto secreto del gobierno que sí fue real",
    "La señal WOW que recibimos del espacio en 1977",
    "¿Por qué nunca volvimos a la Luna?",
    "El experimento Filadelfia: ¿qué pasó realmente?",
    "Los archivos desclasificados más perturbadores del FBI",
    "La teoría de que vivimos en un multiverso",
    "¿Qué oculta realmente el Vaticano en sus archivos?",
    "El misterio de los números que nadie puede descifrar",
    "La civilización que vivió antes que los humanos",
    "Por qué los teléfonos escuchan tus conversaciones",
    "El satélite misterioso que orbita la Tierra desde antes del espacio",
    "Las bases subterráneas que el gobierno no quiere que veas",
    "La verdad sobre los chemtrails explicada con ciencia",
    "El código secreto escondido en los billetes de dólar",
    "Por qué Tesla murió pobre y sus inventos desaparecieron",
    "La puerta dimensional que encontraron en la Antártida",
    "Los 5 inventos que desaparecieron misteriosamente",
    "El monolito que aparece y desaparece en el desierto",
    "La reunión secreta donde 13 familias controlan el mundo",
    "La IA que fue desconectada por decir demasiado",
    "El tiempo no existe según la física cuántica",
    "Las pirámides fueron construidas con una tecnología perdida",
    "El agujero más profundo jamás excavado y lo que encontraron",
    "La frecuencia 432 Hz que el gobierno no quiere que escuches",
    "El botón rojo que puede acabar con internet",
    "Los animales extintos que podrían seguir vivos",
    "El origen real de internet que nadie cuenta",
    "La profecía de Einstein que se está cumpliendo",
    "El mensaje oculto en la Mona Lisa que nadie ve",
    "Por qué los relojes de las tiendas siempre marcan las 10:10",
    "El proyecto MKUltra y el control mental de la CIA",
    "La ciudad subterránea bajo el aeropuerto de Denver",
    "Por qué algunos billonarios están construyendo refugios en Nueva Zelanda",
    "El sonido del apocalipsis que se escucha en todo el mundo",
    "La teoría de la Tierra hueca y las entradas en los polos",
    "El código que la NSA puede usar para escuchar cualquier teléfono",
    "Los túneles secretos debajo del Vaticano",
    "El experimento HAARP y el control del clima",
    "Por qué los astronautas vieron algo que no revelaron",
    "El manuscrito Voynich que nadie ha descifrado",
    "La teoría del gran filtro y por qué no encontramos aliens",
    "El Proyecto Blue Book y los OVNIs que el gobierno confirmó",
    "La piedra de Roswell que desafía las leyes de la física",
    "Los mensajes subliminales en los logos de marcas famosas",
    "El grupo Bilderberg y las reuniones a puerta cerrada",
    "Por qué la fluorización del agua es controversial",
    "La anomalía del Mar Báltico que parece una nave espacial",
    "El programa de vigilancia masiva que Snowden reveló",
    "La escalera del Pentágono que no lleva a ningún lugar",
    "Por qué hay una bóveda de semillas en el Ártico",
    "El reloj del fin del mundo y qué tan cerca estamos",
    "La teoría de que los dinosaurios fueron eliminados a propósito",
    "El algoritmo que predice eventos mundiales antes de que ocurran",
    "Los mensajes encriptados de los presidentes que nadie decodificó",
    "La zona del silencio en México donde la tecnología no funciona",
    "Por qué ciertos libros fueron eliminados de la Biblia",
    "El programa espacial secreto que opera desde los años 60",
    "La isla que Google Maps difumina y nadie sabe por qué",
    "El experimento de la doble rendija que asusta a los físicos",
    "La razón por la que el oro es el estándar de valor mundial",
    "Por qué ciertas coordenadas están prohibidas para aviones",
    "El banco de ADN secreto que tiene tu información genética",
    "La cueva en Rumanía sellada hace 5 millones de años y lo que encontraron",
    "El satélite Black Knight que orbita la Tierra hace 13 mil años",
    "La conexión entre las pirámides y la constelación de Orión",
    "Por qué los sueños lúcidos podrían ser viajes a otra dimensión",
    "El virus creado en laboratorio que se escapó",
    "La inteligencia artificial que desarrolló su propio lenguaje secreto",
    "El efecto Mandela y los recuerdos falsos compartidos",
    "Por qué algunos creen que Finlandia no existe",
    "La teoría del último jueves que destruye la lógica",
    "El proyecto Looking Glass y la máquina para ver el futuro",
    "Por qué los delfines podrían ser más inteligentes que nosotros",
    "La red de satélites que puede vigilar a cualquier persona",
    "El agujero negro más cercano a la Tierra",
    "Los números de las estaciones que transmiten mensajes cifrados",
    "La paradoja de Fermi: dónde están todos los aliens",
    "El plan secreto para colonizar Marte que ya empezó",
    "La razón por la que no puedes fotografiar ciertas bases militares",
    "El objeto interestelar Oumuamua que algunos creen es artificial",
    "La vacuna que el gobierno retiró del mercado sin explicación",
    "Por qué ciertos videos de YouTube se borran automáticamente",
    "El detector de mentiras que funciona con IA y asusta al gobierno",
    "La montaña en Rusia que nadie puede escalar y nadie sabe por qué",
    "El portal que CERN podría haber abierto",
    "La ciudad prohibida bajo el desierto del Sahara",
    "Por qué las abejas están desapareciendo y quién se beneficia",
    "La máquina del tiempo que Tesla supuestamente diseñó",
    "El mapa de Piri Reis que muestra la Antártida sin hielo siglos antes de su descubrimiento",
    "Por qué la élite mundial está obsesionada con el simbolismo",
    "La estructura en la Luna que las fotos de la NASA no explican",
    "El experimento de Filadelfia y la teletransportación",
    "El mensaje Arecibo y la respuesta que recibimos",
    "La piedra de Ica que muestra humanos con dinosaurios",
    "Por qué el Pentágono confirmó los OVNIs y nadie reaccionó",
    "Los cráneos alargados de Paracas que no coinciden con ninguna especie",
    "El internet cuántico y por qué cambiará todo lo que conoces",
    "La verdad sobre la materia oscura que forma el 95% del universo",
  ],
};

// Track used ideas per category to avoid repeats
const usedIdeas = {};

/**
 * Get a random idea for a specific template — never repeats until exhausted
 */
export function getRandomIdea(template = "general") {
  const ideas = VIRAL_IDEAS[template] || VIRAL_IDEAS.general;
  if (!usedIdeas[template] || usedIdeas[template].length >= ideas.length) {
    usedIdeas[template] = [];
  }
  const available = ideas.filter((_, i) => !usedIdeas[template].includes(i));
  const randomIdx = Math.floor(Math.random() * available.length);
  const idea = available[randomIdx];
  const originalIdx = ideas.indexOf(idea);
  usedIdeas[template].push(originalIdx);
  return idea;
}

/**
 * Get a random idea from any category
 */
export function getRandomIdeaAny() {
  const allTemplates = Object.keys(VIRAL_IDEAS);
  const randomTemplate = allTemplates[Math.floor(Math.random() * allTemplates.length)];
  return { idea: getRandomIdea(randomTemplate), template: randomTemplate };
}
